name: Code Review
on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Code Review
        uses: hilltop-tech/ai-codereviewer@v3.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODEL_PROVIDER: "google"
          GOOGLEAI_API_KEY: ${{ secrets.GOOGLEAI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          API_MODEL: "gemini-1.5-pro-exp-0827"
          LANGUAGE: "Japanese"
          max_tokens: 8182
          exclude: "yarn.lock,dist/**"
